### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by donavanbecker**
* Converted to Typescript
* Added config.schema.json for Homebridge UI Support
* Move version up to 1.0.0

### CODE REVIEW

**Comment by donavanbecker** [comment]
@ilcato any thoughts? not completely done with convert but getting there.

**Comment by donavanbecker** [comment]
I think I am done, you might want to look over it and change it how you want.

**Comment by donavanbecker** [comment]
@ilcato what are the chance of getting this merged? or should I just close this PR?

**Comment by ilcato** [comment]
@donavanbecker, I'm not able to test it. I merged it into master but I will not publish it on nom before testing. 
In the mean time: in line 95 of index.ts, why
`this.accessory = new IFTTTAccessory(services);`
and not:
`accessory = new IFTTTAccessory(services);`

**Comment by donavanbecker** [comment]
that is just how I have done some of my other plugins, but it would work with what you have so go ahead and change.

@ilcato are you wanting to continue to maintain this plugin? or would you want to push your plugin to the [unmaintained plugins organization](https://github.com/homebridge-plugins/Info)?

**Comment by ilcato** [comment]
> that is just how I have done some of my other plugins, but it would work with what you have so go ahead and change.
> 

Does it works? I mean, the variable accessory is always empty.

**Comment by donavanbecker** [comment]
@ilcato Yes

**Comment by ilcato** [comment]
Yea, try with the other assignment.

**Comment by donavanbecker** [comment]
@ilcato Since homebridge 1.3.0 has come out, I will get the plugin up to par for it and the push my working changes then it will be good for a while.

**Comment by ilcato** [comment]
@donavanbecker, thanks

**Comment by donavanbecker** [comment]
@ilcato if we change it to `accessory` it causes this error:
```
[2/23/2021, 10:36:47 AM] RangeError: Maximum call stack size exceeded
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
    at IFTTTAccessory.accessory.getServices (/Users/donavanbecker/GitHub/homebridge-ifttt/src/index.ts:99:23)
```
but with this.accessory it works as expected.

**Comment by ilcato** [comment]
@donavanbecker, if I try to publish on NPM I receive the error (can you put const instead of let in line 58 and retest it) :

`homebridge-ifttt % npm publish

> homebridge-ifttt@1.0.0 prepublishOnly .
> npm run lint && npm run build


> homebridge-ifttt@1.0.0 lint /Users/ilcato/Projects/homebridge-ifttt
> eslint src/**.ts


/Users/ilcato/Projects/homebridge-ifttt/src/index.ts
  58:11  error  'accessory' is never reassigned. Use 'const' instead  prefer-const

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-ifttt@1.0.0 lint: `eslint src/**.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge-ifttt@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ilcato/.npm/_logs/2021-02-23T17_02_29_568Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-ifttt@1.0.0 prepublishOnly: `npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge-ifttt@1.0.0 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ilcato/.npm/_logs/2021-02-23T17_02_29_615Z-debug.log
homebridge-ifttt %`

**Comment by donavanbecker** [comment]
yep I did that works sorry that was the one thing I needed to change after looking to over again.

**Comment by ilcato** [comment]
Ok, I will make the change and publish version 1.0.0

**Comment by ilcato** [comment]
Published, can you test it?.

**Comment by donavanbecker** [comment]
@ilcato 
```
[23/02/2021, 16:10:57] [IFTTT] Initializing IFTTT platform...
[23/02/2021, 16:10:57] [IFTTT] Loading accessories...
[23/02/2021, 16:10:57] [IFTTT] Found: Testing
[23/02/2021, 16:10:57] [IFTTT] Loading service: , subtype: test-vnull-vOnnull-vOffnull
```
and never did this before.

**Comment by ilcato** [comment]
If you leave ‘let’ instead of ‘const’ in your installation ?

**Comment by donavanbecker** [comment]
No I changed it. When I first opened the PR it worked though.

**Comment by ilcato** [comment]
@donavanbecker, there were several errors in the migration to typescript. Try version on master.

**Comment by donavanbecker** [comment]
@ilcato the accessory now adds to the home app but doesn't trigger anything.

**Comment by ilcato** [comment]
@donavanbecker, other conversion errors. Try now.

**Comment by donavanbecker** [comment]
@ilcato yes we are good to go! Thanks for fixing this!

Sorry for not having it all ready for you!

**Comment by ilcato** [comment]
Published version 1.0.1

**Comment by donavanbecker** [comment]
@ilcato Thanks!

**Pull request merged**
